### ISSUE TITLE
Error with 

### ISSUE THREAD

**Issue by magillus** [fluttercommunity/responsive_scaffold#3]
stacktrace:
```
2019-06-01 07:59:17.358 29040-29081/com.example.path_manager I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2019-06-01 07:59:17.375 29040-29081/com.example.path_manager I/flutter: The following _CompileTimeError was thrown building LayoutBuilder:
2019-06-01 07:59:17.375 29040-29081/com.example.path_manager I/flutter: 'package:responsive_scaffold/templates/3-column/three_column_navigation.dart': error:
2019-06-01 07:59:17.375 29040-29081/com.example.path_manager I/flutter: file:///C:/Users/magillus/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/responsive_scaffold-1.1.0+3/lib/templates/3-column/three_column_navigation.dart:120:21:
2019-06-01 07:59:17.375 29040-29081/com.example.path_manager I/flutter: Error: No named parameter with the name 'drawerScrimColor'.
2019-06-01 07:59:17.375 29040-29081/com.example.path_manager I/flutter:                     drawerScrimColor: Colors.transparent,
2019-06-01 07:59:17.375 29040-29081/com.example.path_manager I/flutter:                     ^^^^^^^^^^^^^^^^
2019-06-01 07:59:17.377 29040-29081/com.example.path_manager I/flutter: When the exception was thrown, this was the stack:
2019-06-01 07:59:17.392 29040-29081/com.example.path_manager I/flutter: #0      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:113:26)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #1      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #2      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #3      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1740:58)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #4      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #5      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1740:13)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #6      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.393 29040-29081/com.example.path_manager I/flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #22     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3013:14)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
2019-06-01 07:59:17.394 29040-29081/com.example.path_manager I/flutter: #24     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
2019-06-01 07:59:17.395 29040-29081/com.example.path_manager I/flutter: #25     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
2019-06-01 07:59:17.395 29040-29081/com.example.path_manager I/flutter: #26     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
2019-06-01 07:59:17.397 29040-29081/com.example.path_manager I/flutter: #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
2019-06-01 07:59:17.398 29040-29081/com.example.path_manager I/flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
2019-06-01 07:59:17.399 29040-29081/com.example.path_manager I/flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
2019-06-01 07:59:17.401 29040-29081/com.example.path_manager I/flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
2019-06-01 07:59:17.402 29040-29081/com.example.path_manager I/flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
2019-06-01 07:59:17.402 29040-29081/com.example.path_manager I/flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
2019-06-01 07:59:17.402 29040-29081/com.example.path_manager I/flutter: #36     _invoke (dart:ui/hooks.dart:219:10)
2019-06-01 07:59:17.402 29040-29081/com.example.path_manager I/flutter: #37     _drawFrame (dart:ui/hooks.dart:178:3)
2019-06-01 07:59:17.403 29040-29081/com.example.path_manager I/flutter: (elided 3 frames from package dart:async)
2019-06-01 07:59:17.403 29040-29081/com.example.path_manager I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.34.0)
[√] VS Code, 32-bit edition (version 1.33.0)
[√] Connected device (1 available)

• No issues found!

```

**Comment by magillus** [comment]
Can't reproduce after flutter upgrade.
```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code (version 1.34.0)
[√] VS Code, 32-bit edition (version 1.34.0)
[√] Connected device (2 available)

• No issues found!
```

**Comment by rodydavis** [comment]
No longer an issue?
